/*****************************AutoGenerated Code : Do not edit *******************************/
// Type generated from Swagger definition

/*
    Swagger Petstore 1.0.0
    

    License:
    MIT
    
*/



    
    export interface IPet  {
        id? : number;
        name? : string;
        tag? : string;
   
    }
         
    export type IPets = Array<IPet>;
    
    export interface IError  {
        code? : number;
        message? : string;
   
    }
     