/*****************************AutoGenerated Code : Do not edit *******************************/
// Type generated from Swagger definition

/*
    Barcode 1.0.1
    Converts barcodes on fake-Key packaging or invoices to
    useful information
*/



    
    /**
     * QRcode from a fake-Key product label. Ensure you are not
     * omitting the special group separator character from the
     * scan (ASCII code 29)
     */
    
    export interface IQRCodeInput  {
        /*
         * QRcode from a fake-Key product label. Ensure you are not
         * omitting the special group separator character
         */
        QRCode? : string;
   
    }
         
    /**
     * Response object containing part information
     */
    
    export interface IBarcodeResponse  {
        /*
         * Status of data lookup.
         * @example Success
         */
        Status? : string;
        /*
         * fake-Key Part Number
         * @example p5555-nd
         */
        fakeKeyPartNumber? : string;
        /*
         * Manufacturer Part Number
         * @example ECA-1VHG102
         */
        ManufacturerPartNumber? : string;
        /*
         * Manufacturer Name
         * @example Panasonic
         */
        ManufacurerName? : string;
        /*
         * Description of part
         * @example CAP ALUM 1000UF 20% 35V RADIAL
         */
        Description? : string;
        /*
         * Quantity of part
         * @example 1
         */
        Quantity? : number;
   
    }
         
    export interface IInvoiceBarcodeResponse  {
        /*
         * Status of data lookup.
         * @example Success
         */
        Status? : string;
        /*
         * Sales Order number
         * @example 12345678
         */
        SalesOrder? : number;
        /*
         * Invoice number
         * @example 12345678
         */
        Invoice? : number;
        /*
         * Packlist page number
         * @example 1
         */
        Packlist? : number;
        /*
         * List of invoice details
         */
        Details? : Array<IInvoiceDetail>;
   
    }
         
    export interface IInvoiceDetail  {
        /*
         * fake-Key part number
         * @example p5555-nd
         */
        fakeKeyPartNumber? : string;
        /*
         * Quantity
         * @example 1
         */
        Quantity? : number;
   
    }
     