/*****************************AutoGenerated Code : Do not edit *******************************/
// Type generated from Swagger definition

/*
    USPTO Data Set API 1.0.0
    The Data Set API (DSAPI) allows the public users to
    discover and search USPTO exported data sets. This is a
    generic API that allows USPTO users to make any CSV based
    data files searchable through API. With the help of GET
    call, it returns the list of data fields that are
    searchable. With the help of POST call, data can be fetched
    based on the filters on the field names. Please note that
    POST call is used to search the actual data. The reason for
    the POST call is that it allows users to specify any
    complex search criteria without worry about the GET size
    limitations as well as encoding of the input parameters.
    
    Contact:
    Open Data Portal
    developer@uspto.gov
    https://developer.uspto.gov
*/



