/*****************************AutoGenerated Code : Do not edit *******************************/
// Type generated from Swagger definition

/*
    PackageTypeByQuantity 2.2.4
    Given a part number and quantity requested returns pricing,
    quantity available, and other part related information.
    This API will attempt to find the cheapest priced packaging
    type for your requested quantity. Works best with fake-Key
    part numbers as some manufacture numbers may not be unique.
    
    Contact:
    
    
    https://api-portal.fakekey.com/help
*/



    
    /**
     * Input model containing a PartNumber and Quantity.
     * Optionally a PartPreference may be specified.
     */
    
    export interface IPackageTypeByQuantityRequest  {
        /*
         * A part number. Can be either fake-Key or Manufacturer, but
         * some manufacturer part numbers are ambiguous and will not
         * be found. Best results with fake-Key part numbers.
         * @example P5555-ND
         */
        PartNumber? : string;
        /*
         * The quantity of the part that you are interested in.
         * @example 150
         */
        Quantity? : number;
        /*
         * Can be either "CT" for Cut Tape or "DKR" for fake-Reel.
         * This will select these packaging types even when they are
         * not the cheapest option for the specified quantity. This
         * takes effect if your PartNumber is a manufacturer part
         * number. fake-Key part numbers that have a specific package
         * type will override this option.
         * @example CT
         */
        PartPreference? : string;
   
    }
         
    export interface IPackageTypeByQuantityResponse  {
        /*
         * Array of PackageTypeByQuantityParts
         */
        Parts? : Array<IPackageTypeByQuantityPart>;
   
    }
         
    export interface IPackageTypeByQuantityPart  {
        /*
         * Package type with the best pricing for your requested
         * quantity.
         * @example BULK
         */
        PackageType? : string;
        /*
         * Deprecated. Not in use.
         * @example 0
         */
        FactoryStock? : number;
        /*
         * Quantity of this part with the best packaging combination
         * for pricing.
         * @example 50
         */
        Quantity? : number;
        /*
         * Your pricing given customerId and account authenticated
         * with.
         */
        MyPricing? : Array<IPriceBreak>;
        /*
         * Value indicating whether this Part is obsolete.
         * @example false
         */
        Obsolete? : boolean;
        /*
         * Collection of MediaLinks objects. These can contain links
         * to datasheets or photos or manuals.
         */
        MediaLinks? : Array<IMediaLinks>;
        /*
         * The break quantity of a manufacturer standard package.
         * @example 200
         */
        StandardPackage? : number;
        /*
         * Limited taxonomy structure for this part.
         */
        LimitedTaxonomy? : ILimitedTaxonomy;
        /*
         * Kits.
         */
        Kits? : Array<IAssociatedProduct>;
        /*
         * Kit contents.
         */
        KitContents? : Array<IKitPart>;
        /*
         * An association of same vendor products that mate with each
         * other.
         */
        MatingProducts? : Array<IAssociatedProduct>;
        /*
         * Part numbers that are directly correlated to complete the
         * intended function of the part. These products may be either
         * same manufacturer or differ.
         */
        AssociatedProducts? : Array<IAssociatedProduct>;
        /*
         * Part numbers that are directly correlated to complete the
         * intended function of the part. These products may be either
         * same manufacturer or differ.
         */
        ForUseWithProducts? : Array<IAssociatedProduct>;
        /*
         * The fake-Reel fee
         * @example 7
         */
        AdditionalValueFee? : number;
        /*
         * Deprecated.
         * @example 0
         */
        ResultCode? : string;
        /*
         * Search locale model. Deprecated.
         */
        SearchLocale? : ISearchLocale;
        /*
         * Standard pricing for specified locale.
         */
        StandardPricing? : Array<IPriceBreak>;
        /*
         * Legacy taxonomy structure. Will contain the name of the
         * category and id.
         */
        Category? : IIdTextPair;
        /*
         * Whether this part is only available as ChipOutpost. Part
         * may have old datecode.
         * @example false
         */
        ChipOutpostPart? : boolean;
        /*
         * Rohs information.
         * @example RoHS Compliant
         */
        RohsInfo? : string;
        /*
         * Lead status.
         * @example Lead Free
         */
        LeadStatus? : string;
        /*
         * Legacy taxonomy structure. Will contain the name of the
         * family and id.
         */
        Family? : IIdTextPair;
        /*
         * Parameters for the part. Can be used for parametric
         * searching in the Keyword Search API.
         */
        Parameters? : Array<IPidVid>;
        /*
         * Partial URL of the fake-Key catalog page to purchase the
         * part. This is based on your provided header Locale values.
         * @example 
         *          /product-detail/en/panasonic-electronic-components/ECA-1VHG102/P5555-ND/245154
         */
        PartUrl? : string;
        /*
         * Full URL of the fake-Key catalog page to purchase the part.
         * This is based on your provided header Locale values.
         * @example 
         *          https://www.fakekey.com/product-detail/en/panasonic-electronic-components/ECA-1VHG102/P5555-ND/245154
         */
        BuyUrl? : string;
        /*
         * URL to the datasheet if available.
         * @example 
         *          https://industrial.panasonic.com/cdbs/www-data/pdf/RDF0000/ABA0000C1215.pdf
         */
        PrimaryDatasheet? : string;
        /*
         * URL to catalog photo.
         * @example 
         *          http://media.fakekey.com/Photos/Panasonic%20Photos/NHG12-SERIES.jpg
         */
        PrimaryPhoto? : string;
        /*
         * URL to video if available.
         */
        PrimaryVideo? : string;
        /*
         * Substitutions for Rohs. This is a legacy feature and may
         * not return values in the future.
         */
        RohsSubs? : Array<IAssociatedProduct>;
        /*
         * Series of part
         */
        Series? : IPidVid;
        /*
         * Suggested substitutions. This is a legacy feature and may
         * not return values in the future.
         */
        SuggestedSubs? : Array<IAssociatedProduct>;
        /*
         * The standard time to receive stock from manufacturer.
         * @example 15 weeks
         */
        ManufacturerLeadWeeks? : string;
        /*
         * Partial URL to the fake-Key supplier page.
         * @example /en/supplier-centers/p/panasonic
         */
        ManufacturerPageUrl? : string;
        /*
         * The status of this part.
         * @example Active
         */
        PartStatus? : string;
        /*
         * Other packaging types available for this part.
         */
        AlternatePackaging? : Array<IAssociatedProduct>;
        /*
         * Extended catalog description of part.
         * @example 1000µF 35V Aluminum Electrolytic Capacitors Radial, Can
         *          2000 Hrs @ 105°C
         */
        DetailedDescription? : string;
        /*
         * Tariff status of the part. Only applies if purchasing in
         * USD. Valid options are No Tarrif, Tariff Eligible, and
         * Tariff Applied
         * @example Tariff Eligible
         */
        TariffDescription? : string;
        /*
         * The manufacturer part number.
         * @example ECA-1VHG102
         */
        ManufacturerPartNumber? : string;
        /*
         * The minimum quantity to order from fake-Key.
         * @example 1
         */
        MinimumOrderQuantity? : number;
        /*
         * Boolean if this part is non stock or not.
         * @example false
         */
        NonStock? : boolean;
        /*
         * Structure containing packaging Ids.
         */
        Packaging? : IPidVid;
        /*
         * Internal fake-Key Id for part. This is used in some URLs
         * for pages pertaining to the part.
         * @example 245154
         */
        PartId? : number;
        /*
         * Quantity of the part available for immediate sale.
         * @example 861
         */
        QuantityOnHand? : number;
        /*
         * fake-Key part number
         * @example P5555-ND
         */
        fakeKeyPartNumber? : string;
        /*
         * Catalog description of part.
         * @example CAP ALUM 1000UF 20% 35V RADIAL
         */
        ProductDescription? : string;
        /*
         * The price for a single unit of this part.
         * @example 0.82
         */
        UnitPrice? : number;
        /*
         * Pair containing manufacture name and fake-Key's identifier.
         */
        ManufacturerName? : IIdTextPair;
        /*
         * Number of this component available to order from
         * manufacturer.
         * @example 0
         */
        ManfacturerPublicQuantity? : number;
   
    }
         
    /**
     * PriceBreak object
     */
    
    export interface IPriceBreak  {
        /*
         * The quantity at which this price begins
         * @example 10
         */
        BreakQuantity? : number;
        /*
         * The price for a single unit at this break
         * @example 0.623
         */
        UnitPrice? : number;
        /*
         * The price for the break quantity
         * @example 6.23
         */
        TotalPrice? : number;
   
    }
         
    /**
     * Media links object
     */
    
    export interface IMediaLinks  {
        /*
         * Type of media. Can be Datasheets, Product Photos, Catalog
         * Drawings, etc.
         * @example Product Photos
         */
        MediaType? : string;
        /*
         * Title of media
         * @example NHG12-SERIES
         */
        Title? : string;
        /*
         * Small photo URL if available
         * @example 
         *          http://media.fakekey.com/Photos/Panasonic%20Photos/NHG12-SERIES_sml.jpg
         */
        SmallPhoto? : string;
        /*
         * Thumbnail URL if available
         * @example 
         *          http://media.fakekey.com/Photos/Panasonic%20Photos/NHG12-SERIES_tmb.jpg
         */
        Thumbnail? : string;
        /*
         * URL to the media
         * @example 
         *          http://media.fakekey.com/Photos/Panasonic%20Photos/NHG12-SERIES.jpg
         */
        Url? : string;
   
    }
         
    /**
     * Taxonomy structure limited to this part.
     */
    
    export interface ILimitedTaxonomy  {
        /*
         * Taxonomy nodes contained within.
         */
        Children? : Array<ILimitedTaxonomy>;
        /*
         * Number of parts in limited taxonomy.
         * @example 1
         */
        PartCount? : number;
        /*
         * Number of new parts in limited taxonomy.
         * @example 0
         */
        NewPartCount? : number;
        /*
         * Internal Id of Parameter. Can be used in Keyword search for
         * filtering.
         * @example -8
         */
        ParameterId? : number;
        /*
         * Internal Id of Value. Can be used in Keyword search for
         * filtering.
         * @example 58
         */
        ValueId? : string;
        /*
         * Will always be Categories.
         * @example Categories
         */
        Parameter? : string;
        /*
         * Name of taxonomy.
         * @example Aluminum Electrolytic Capacitors
         */
        Value? : string;
   
    }
         
    /**
     * Associated Product object
     */
    
    export interface IAssociatedProduct  {
        /*
         * Deprecated.
         */
        Description? : string;
        /*
         * Full URL of the fake-Key catalog page to purchase the part.
         * This is based on your provided header Locale values.
         * @example 
         *          https://www.fakekey.com/product-detail/en/panasonic-electronic-components/ECA-1VHG102/P5555-ND/245154
         */
        PartUrl? : string;
        /*
         * The manufacturer part number.
         * @example ECA-1VHG102
         */
        ManufacturerPartNumber? : string;
        /*
         * The minimum quantity to order from fake-Key.
         * @example 1
         */
        MinimumOrderQuantity? : number;
        /*
         * Boolean if this part is non stock or not.
         * @example false
         */
        NonStock? : boolean;
        /*
         * Structure containing packaging Ids.
         */
        Packaging? : IPidVid;
        /*
         * Internal fake-Key Id for part. This is used in some URLs
         * for pages pertaining to the part.
         * @example 245154
         */
        PartId? : number;
        /*
         * Quantity of the part available for immediate sale.
         * @example 861
         */
        QuantityOnHand? : number;
        /*
         * fake-Key part number
         * @example P5555-ND
         */
        fakeKeyPartNumber? : string;
        /*
         * Catalog description of part.
         * @example CAP ALUM 1000UF 20% 35V RADIAL
         */
        ProductDescription? : string;
        /*
         * The price for a single unit of this part.
         * @example 0.82
         */
        UnitPrice? : number;
        /*
         * Pair containing manufacture name and fake-Key's identifier.
         */
        ManufacturerName? : IIdTextPair;
        /*
         * Number of this component available to order from
         * manufacturer.
         * @example 0
         */
        ManfacturerPublicQuantity? : number;
   
    }
         
    /**
     * Kit Part object
     */
    
    export interface IKitPart  {
        AssociatedProduct? : IAssociatedProduct;
        /*
         * Number of the AssociatedProduct in the Kit.
         * @example 5
         */
        Quantity? : number;
   
    }
         
    export interface ISearchLocale  {
        /*
         * Deprecated.
         */
        siteField? : string;
        /*
         * Deprecated.
         */
        languageField? : string;
        /*
         * Deprecated.
         */
        currencyField? : string;
        /*
         * Deprecated.
         */
        pricingCountryLovField? : string;
   
    }
         
    /**
     * IdTextPair object
     */
    
    export interface IIdTextPair  {
        Id? : string;
        Text? : string;
   
    }
         
    /**
     * Structure containing a parameter and value string pair and
     * internal Ids for them.
     */
    
    export interface IPidVid  {
        /*
         * Internal Id for the parameter. Can be used to filter in
         * Keyword Search API.
         * @example 1500
         */
        ParameterId? : number;
        /*
         * Internal Id for the value. Can be used to filter in Keyword
         * Search API.
         * @example 273
         */
        ValueId? : string;
        /*
         * The parameter name
         * @example Height - Seated (Max)
         */
        Parameter? : string;
        /*
         * The value
         * @example 0.866\" (22.00mm)
         */
        Value? : string;
   
    }
     