/*****************************AutoGenerated Code : Do not edit *******************************/
// Type generated from Swagger definition

/*
    Swagger Petstore 1.0.0
    A sample API that uses a petstore as an example to
    demonstrate features in the swagger-2.0 specification
    
    Contact:
    Swagger API Team
    
    

    License:
    MIT
    
*/



    
    export interface IPet  {
   
    }
         
    export interface INewPet  {
        name? : string;
        tag? : string;
   
    }
         
    export interface IErrorModel  {
        code? : number;
        message? : string;
   
    }
     