/*****************************AutoGenerated Code : Do not edit *******************************/
// Type generated from Swagger definition

/*
    Swagger Petstore 1.0.0
    

    License:
    MIT
    
*/



