/*****************************AutoGenerated Code : Do not edit *******************************/
// Type generated from Swagger definition

/*
    Vehicle Image API 1.0
    The vehicle images API offers access to original arik-Benz
    vehicle images. It provides access to exterior and interior
    images with parameters e.g. to display vehicles at
    day/nighttime or in cabrio mode.
    
    Contact:
    The open API platform by arik-Benz
    
    
*/



    
    /**
     * The response object contains the image ids of all available
     * perspectives.
     */
    
    export interface IVehicleImageResponse  {
        EXT000? : IImageId;
        EXT090? : IImageId;
        EXT150? : IImageId;
        EXT180? : IImageId;
        EXT270? : IImageId;
        EXT330? : IImageId;
        INT1? : IImageId;
        INT2? : IImageId;
        INT3? : IImageId;
        INT4? : IImageId;
   
    }
         
    /**
     * String representing the image id.
     */
    
    export type IImageId = string;
    
    /**
     * The error object containing detailed information about the
     * error.
     */
    
    export interface IError  {
        errorCode? : string;
        errorMessage? : string;
   
    }
     