/*****************************AutoGenerated Code : Do not edit *******************************/
// Type generated from Swagger definition

/*
    Uber API 1.0.0
    Move your app forward with the Uber API
*/



    
    export interface IProduct  {
        /*
         * Unique identifier representing a specific product for a
         * given latitude & longitude. For example, uberX in San
         * Francisco will have a different product_id than uberX in
         * Los Angeles.
         */
        product_id? : string;
        /*
         * Description of product.
         */
        description? : string;
        /*
         * Display name of product.
         */
        display_name? : string;
        /*
         * Capacity of product. For example, 4 people.
         */
        capacity? : string;
        /*
         * Image URL representing the product.
         */
        image? : string;
   
    }
         
    export interface IPriceEstimate  {
        /*
         * Unique identifier representing a specific product for a
         * given latitude & longitude. For example, uberX in San
         * Francisco will have a different product_id than uberX in
         * Los Angeles
         */
        product_id? : string;
        /*
         * [ISO 4217](http://en.wikipedia.org/wiki/ISO_4217) currency
         * code.
         */
        currency_code? : string;
        /*
         * Display name of product.
         */
        display_name? : string;
        /*
         * Formatted string of estimate in local currency of the start
         * location. Estimate could be a range, a single number (flat
         * rate) or "Metered" for TAXI.
         */
        estimate? : string;
        /*
         * Lower bound of the estimated price.
         */
        low_estimate? : number;
        /*
         * Upper bound of the estimated price.
         */
        high_estimate? : number;
        /*
         * Expected surge multiplier. Surge is active if
         * surge_multiplier is greater than 1. Price estimate already
         * factors in the surge multiplier.
         */
        surge_multiplier? : number;
   
    }
         
    export interface IProfile  {
        /*
         * First name of the Uber user.
         */
        first_name? : string;
        /*
         * Last name of the Uber user.
         */
        last_name? : string;
        /*
         * Email address of the Uber user
         */
        email? : string;
        /*
         * Image URL of the Uber user.
         */
        picture? : string;
        /*
         * Promo code of the Uber user.
         */
        promo_code? : string;
   
    }
         
    export interface IActivity  {
        /*
         * Unique identifier for the activity
         */
        uuid? : string;
   
    }
         
    export interface IActivities  {
        /*
         * Position in pagination.
         */
        offset? : number;
        /*
         * Number of items to retrieve (100 max).
         */
        limit? : number;
        /*
         * Total number of items available.
         */
        count? : number;
        history? : Array<IActivity>;
   
    }
         
    export interface IError  {
        code? : number;
        message? : string;
        fields? : string;
   
    }
     