/*****************************AutoGenerated Code : Do not edit *******************************/
// Type generated from Swagger definition

/*
    OrderHistory 1.1.4
    Retrieve list of sales order IDs for a given account to be
    looked up with the order status API.
*/



    
    /**
     * Information pertaining to a single sales order
     */
    
    export interface ISalesOrderHistoryItem  {
        /*
         * The sales order ID
         */
        SalesOrderId? : number;
        /*
         * The customer ID associated with the sales order
         */
        CustomerId? : number;
        /*
         * Date in which the order was entered formatted as MM/dd/yyyy
         * HH:mm:ss tt. Note that in a future release this will be
         * changed to ISO 8601.
         * @example 3/14/2017 12:50:12 PM
         */
        DateEntered? : string;
        /*
         * Purchase order if available
         * @example Example Order
         */
        PurchaseOrder? : string;
   
    }
     