/*****************************AutoGenerated Code : Do not edit *******************************/
// Type generated from Swagger definition

/*
    Swagger Petstore 1.0.0
    A sample API that uses a petstore as an example to
    demonstrate features in the OpenAPI 3.0 specification
    
    Contact:
    Swagger API Team
    apiteam@swagger.io
    http://swagger.io

    License:
    Apache 2.0
    https://www.apache.org/licenses/LICENSE-2.0.html
*/



