/*****************************AutoGenerated Code : Do not edit *******************************/
// Type generated from Swagger definition

/*
    Product Change Notifications 1.0.3
    This API provides all product change notifications for a
    given fake-Key part.
    
    Contact:
    
    
    https://api-portal.fakekey.com/help
*/



    
    /**
     * This contains an array of PCN data responses.
     */
    
    export interface IPcnResponse  {
        /*
         * The fake-Key part number being submitted.
         * @example PN200A-ND
         */
        fakeKeyPartNumber? : string;
        /*
         * An array of PCNDataResponses.
         */
        ProductChangeNotifications? : Array<IPcnDataResponse>;
   
    }
         
    /**
     * This contains the details of each product change
     * notification.
     */
    
    export interface IPcnDataResponse  {
        /*
         * The fake-Key part number being submitted.
         * @example PN200A-ND
         */
        fakeKeyPartNumber? : string;
        /*
         * The date of the product change notification - ISO 8601
         * @example 2018-11-26T20:49:13Z
         */
        PcnChangeDate? : string;
        /*
         * The product change notification type id.
         * @example 38
         */
        PcnTypeId? : string;
        /*
         * The description of the product change notification type.
         * @example PCN Design/Specification
         */
        PcnType? : string;
        /*
         * A brief description of the change.
         * @example Logo 17/Aug/2017
         */
        PcnDescription? : string;
        /*
         * A link to a document detailing the product change.
         * @example https://media.fakekey.com/pdf/PCNs/On%20Semi/P774AAB.pdf
         */
        PcnLink? : string;
   
    }
     