/*****************************AutoGenerated Code : Do not edit *******************************/
// Type generated from Swagger definition

/*
    Binary Server 1.0.0
    
*/



    
    export interface ISwaggerInlineType1  {
        /*
         * url to retrieve
         */
        url? : string;
   
    }
     