/*****************************AutoGenerated Code : Do not edit *******************************/
// Type generated from Swagger definition

/*
    Recommended Parts 2.0.2
    API to provide recommended parts for given PartNumber.
    These are parts that you may be interested in given your
    interest in the provided part number.
    
    Contact:
    
    
    
*/



    
    export interface IRecommendedPartsRequestV2  {
        /*
         * List of searchOption types to be used for the search
         */
        SearchOptionList? : Array<string>;
        /*
         * Maximum number of recommendations to return.
         * @example 5
         */
        RecordCount? : number;
        /*
         * Part number to get recommendations for. Can be fake-Key or
         * Manufacturer. Not all parts have recommendations.
         * @example cr2032
         */
        PartNumber? : string;
   
    }
         
    export interface IRecommendedPartsResponseV2  {
        /*
         * List of RecommendedPartsCollections - each containing a
         * Part and its recommendations.
         */
        RecommendedPartsCollection? : Array<IRecommendedPartsCollectionV2>;
   
    }
         
    export interface IRecommendedPartsCollectionV2  {
        /*
         * The part number that the recommendations are for.
         * @example P5555-ND
         */
        PartNumber? : string;
        /*
         * A part that you may be interested in.
         */
        RecommendedParts? : Array<IRecommendedPartV2>;
   
    }
         
    export interface IErrorResponse  {
        /*
         * The HTTP status code.
         * @example 503
         */
        HttpStatusCode? : number;
        /*
         * Message describing the error.
         * @example Service is unavailable
         */
        Message? : string;
   
    }
         
    /**
     * Lightweight part object containing basic part information.
     */
    
    export interface IRecommendedPartV2  {
        /*
         * fake-Key part number.
         * @example P5555-ND
         */
        fakeKeyPartNumber? : string;
        /*
         * The manufacturer part number.
         * @example ECA-1VHG102
         */
        ManufacturerPartNumber? : string;
        /*
         * The name of the manufacturer.
         * @example Panasonic
         */
        ManufacturerName? : string;
        /*
         * Image URL if available.
         * @example 
         *          http://media.fakekey.com/Photos/Panasonic%20Photos/NHG12-SERIES_tmb.jpg
         */
        ImageUrl? : string;
        /*
         * Catalog description of part.
         * @example CAP ALUM 1000UF 20% 35V RADIAL
         */
        CatalogDescription? : string;
        /*
         * Quantity of the part available for immediate sale.
         * @example 85107
         */
        QuantityAvailable? : number;
        /*
         * The catalog price for a single unit of this part.
         * @example 0.82
         */
        UnitPrice? : number;
        /*
         * URL of the fake-Key catalog page to purchase the part. This
         * is based on your provided header Locale values.
         * @example 
         *          /product-detail/en/panasonic-electronic-components/ECA-1VHG102/P5555-ND/245154
         */
        DetailPageUrl? : string;
   
    }
     