/*****************************AutoGenerated Code : Do not edit *******************************/
// Type generated from Swagger definition

/*
    PartSearch 2.3.4
    Search for parts in the fake-Key catalog by keyword using
    KeywordSearch. Then make a PartDetails call to retrieve all
    real time information about the part including pricing.
    PartDetails works best with fake-Key part numbers as some
    manufacturers overlap other manufacturer part numbers.
    
    Contact:
    
    
    https://api-portal.fakekey.com/help
*/



    
    /**
     * Request model for KeywordSearch
     */
    
    export interface IKeywordSearchPostRequest  {
        /*
         * Filters the search results by the included SearchOptions.
         */
        SearchOptions? : Array<string>;
        /*
         * Keywords to search on.
         * @example p5555-nd
         */
        Keywords? : string;
        /*
         * Number of parts to return,  1-50
         * @example 10
         */
        RecordCount? : number;
        /*
         * Starting index of the records returned.
         * @example 0
         */
        RecordStartPosition? : number;
        /*
         * Set Filters to narrow down search response.
         */
        Filters? : IFilter;
        /*
         * Sort Parameters
         */
        Sort? : ISortParameters;
        /*
         * The RequestedQuantity is used with the SortByUnitPrice Sort
         * Option to sort by unit price at the RequestedQuantity.
         * @example 50
         */
        RequestedQuantity? : number;
   
    }
         
    /**
     * Set Filters to narrow down the search results.
     */
    
    export interface IFilter  {
        /*
         * A collection of Category IDs to filter on. Deprecated.
         */
        CategoryIds? : Array<number>;
        /*
         * A collection of Family IDs to filter on. Deprecated.
         */
        FamilyIds? : Array<number>;
        /*
         * A collection of Manufacturer IDs to filter on.
         */
        ManufacturerIds? : Array<number>;
        /*
         * A collection of ParametricFilters. Filter by any PidVid.
         */
        ParametricFilters? : Array<IParametricFilter>;
   
    }
         
    /**
     * SortParameters - All properties are required if used.
     */
    
    export interface ISortParameters  {
        /*
         * Specifies the field to sort on. Options include
         * SortByfakeKeyPartNumber, SortByManufacturerPartNumber,
         * SortByDescription, SortByCategory, SortByFamily,
         * SortByManufacturer, SortByMinimumOrderQuantity,
         * SortByQuantityAvailable, SortByUnitPrice, SortByParameter.
         * @example SortByUnitPrice
         */
        Option? : string;
        /*
         * The sort direction - Ascending or Decending
         * @example Ascending
         */
        Direction? : string;
        /*
         * The ParameterId of the parameter to sort on. Only used if
         * Option is SortByParameter, but is required. If using other
         * Options, input 0.
         * @example 50
         */
        SortParameterId? : number;
   
    }
         
    /**
     * Parametric Filter object. You can narrow down your searches
     * using PidVids. Unfortunately a full list is unavailable.
     */
    
    export interface IParametricFilter  {
        /*
         * Internal Id representing a parameter.
         * @example 725
         */
        ParameterId? : number;
        /*
         * Internal Id representing a value.
         * @example 7
         */
        ValueId? : string;
   
    }
         
    /**
     * Http Response for KeywordSearch
     */
    
    export interface IKeywordSearchPostResponse  {
        /*
         * List of parts returned by KeywordSearch
         */
        Parts? : Array<IPart>;
        /*
         * Limited taxonomy structure for this part.
         */
        Taxonomy? : ILimitedTaxonomy;
        /*
         * Legacy taxonomy structure. Will contain the name of the
         * category and id.
         */
        LimitedCategories? : Array<ILimitedCategory>;
        FilterValues? : Array<IPidVid>;
        /*
         * PidVids relating to this part. These can be used for
         * parametric searching.
         */
        LimitedFilterValues? : Array<ILimitedParameter>;
        /*
         * Total number of parts returned
         * @example 20
         */
        Results? : number;
        /*
         * Number of exact manufacturer number matches.
         * @example 1
         */
        ExactMatches? : number;
        /*
         * List of parts that are exact manufacturer number matches.
         */
        ExactParts? : Array<IPart>;
        /*
         * Part that matches fake-Key part number search exactly.
         */
        ExactfakeKeyPart? : IPart;
   
    }
         
    /**
     * PartSearch part Data Transfer Object
     */
    
    export interface IPart  {
        /*
         * Standard pricing. This is cached catalog pricing for a
         * given fake-Key site. Data is cached for 24 hours.
         */
        StandardPricing? : Array<IPriceBreak>;
        /*
         * Your pricing only when making PartDetail call. Keyword
         * Search is cached values only.
         */
        MyPricing? : Array<IPriceBreak>;
        /*
         * Legacy taxonomy structure. Will contain the name of the
         * category and id.
         */
        Category? : IIdTextPair;
        /*
         * Whether this part is only available as ChipOutpost. Part
         * may have old datecode.
         * @example false
         */
        ChipOutpostPart? : boolean;
        /*
         * Rohs information.
         * @example RoHS Compliant
         */
        RohsInfo? : string;
        /*
         * Lead status.
         * @example Lead Free
         */
        LeadStatus? : string;
        /*
         * Legacy taxonomy structure. Will contain the name of the
         * family and id.
         */
        Family? : IIdTextPair;
        /*
         * Parameters for the part. Can be used for parametric
         * searching in the Keyword Search API.
         */
        Parameters? : Array<IPidVid>;
        /*
         * Partial URL of the fake-Key catalog page to purchase the
         * part. This is based on your provided header Locale values.
         * @example 
         *          /product-detail/en/panasonic-electronic-components/ECA-1VHG102/P5555-ND/245154
         */
        PartUrl? : string;
        /*
         * Full URL of the fake-Key catalog page to purchase the part.
         * This is based on your provided header Locale values.
         * @example 
         *          https://www.fakekey.com/product-detail/en/panasonic-electronic-components/ECA-1VHG102/P5555-ND/245154
         */
        BuyUrl? : string;
        /*
         * URL to the datasheet if available.
         * @example 
         *          https://industrial.panasonic.com/cdbs/www-data/pdf/RDF0000/ABA0000C1215.pdf
         */
        PrimaryDatasheet? : string;
        /*
         * URL to catalog photo.
         * @example 
         *          http://media.fakekey.com/Photos/Panasonic%20Photos/NHG12-SERIES.jpg
         */
        PrimaryPhoto? : string;
        /*
         * URL to video if available.
         */
        PrimaryVideo? : string;
        /*
         * Substitutions for Rohs. This is a legacy feature and may
         * not return values in the future.
         */
        RohsSubs? : Array<IAssociatedProduct>;
        /*
         * Series of part
         */
        Series? : IPidVid;
        /*
         * Suggested substitutions. This is a legacy feature and may
         * not return values in the future.
         */
        SuggestedSubs? : Array<IAssociatedProduct>;
        /*
         * The standard time to receive stock from manufacturer.
         * @example 15 weeks
         */
        ManufacturerLeadWeeks? : string;
        /*
         * Partial URL to the fake-Key supplier page.
         * @example /en/supplier-centers/p/panasonic
         */
        ManufacturerPageUrl? : string;
        /*
         * The status of this part.
         * @example Active
         */
        PartStatus? : string;
        /*
         * Other packaging types available for this part.
         */
        AlternatePackaging? : Array<IAssociatedProduct>;
        /*
         * Extended catalog description of part.
         * @example 1000µF 35V Aluminum Electrolytic Capacitors Radial, Can
         *          2000 Hrs @ 105°C
         */
        DetailedDescription? : string;
        /*
         * Tariff status of the part. Only applies if purchasing in
         * USD. Valid options are No Tarrif, Tariff Eligible, and
         * Tariff Applied
         * @example Tariff Eligible
         */
        TariffDescription? : string;
        /*
         * The manufacturer part number.
         * @example ECA-1VHG102
         */
        ManufacturerPartNumber? : string;
        /*
         * The minimum quantity to order from fake-Key.
         * @example 1
         */
        MinimumOrderQuantity? : number;
        /*
         * Boolean if this part is non stock or not.
         * @example false
         */
        NonStock? : boolean;
        /*
         * Structure containing packaging Ids.
         */
        Packaging? : IPidVid;
        /*
         * Internal fake-Key Id for part. This is used in some URLs
         * for pages pertaining to the part.
         * @example 245154
         */
        PartId? : number;
        /*
         * Quantity of the part available for immediate sale.
         * @example 861
         */
        QuantityOnHand? : number;
        /*
         * fake-Key part number
         * @example P5555-ND
         */
        fakeKeyPartNumber? : string;
        /*
         * Catalog description of part.
         * @example CAP ALUM 1000UF 20% 35V RADIAL
         */
        ProductDescription? : string;
        /*
         * The price for a single unit of this part.
         * @example 0.82
         */
        UnitPrice? : number;
        /*
         * Pair containing manufacture name and fake-Key's identifier.
         */
        ManufacturerName? : IIdTextPair;
        /*
         * Number of this component available to order from
         * manufacturer.
         * @example 0
         */
        ManfacturerPublicQuantity? : number;
   
    }
         
    /**
     * object for LimitedTaxonomy
     */
    
    export interface ILimitedTaxonomy  {
        /*
         * Taxonomy nodes contained within.
         */
        Children? : Array<ILimitedTaxonomy>;
        /*
         * Number of parts in limited taxonomy.
         * @example 1
         */
        PartCount? : number;
        /*
         * Number of new parts in limited taxonomy.
         * @example 0
         */
        NewPartCount? : number;
        /*
         * Internal Id of Parameter. Can be used in Keyword search for
         * filtering.
         * @example -8
         */
        ParameterId? : number;
        /*
         * Internal Id of Value. Can be used in Keyword search for
         * filtering.
         * @example 58
         */
        ValueId? : string;
        /*
         * Will always be Categories.
         * @example Categories
         */
        Parameter? : string;
        /*
         * Name of taxonomy.
         * @example Aluminum Electrolytic Capacitors
         */
        Value? : string;
   
    }
         
    /**
     * Limited Category object. Legacy taxonomy structure.
     */
    
    export interface ILimitedCategory  {
        /*
         * Internal Id of Category.
         * @example 2
         */
        Id? : string;
        /*
         * String representation of category.
         * @example Capacitors
         */
        Category? : string;
        /*
         * Families contained in category.
         */
        Families? : Array<IFamily>;
   
    }
         
    /**
     * Structure containing a parameter and value string pair and
     * internal Ids for them.
     */
    
    export interface IPidVid  {
        /*
         * Internal Id for the parameter. Can be used to filter in
         * Keyword Search API.
         * @example 1500
         */
        ParameterId? : number;
        /*
         * Internal Id for the value. Can be used to filter in Keyword
         * Search API.
         * @example 273
         */
        ValueId? : string;
        /*
         * The parameter name.
         * @example Height - Seated (Max)
         */
        Parameter? : string;
        /*
         * The value.
         * @example 0.866\" (22.00mm)
         */
        Value? : string;
   
    }
         
    /**
     * Limited Parameter
     */
    
    export interface ILimitedParameter  {
        /*
         * Array of values
         */
        Values? : Array<IValue>;
        /*
         * Internal Id for the parameter. Can be used to filter in
         * Keyword Search API.
         * @example -1
         */
        Pid? : number;
        /*
         * The parameter name
         * @example Manufacturer
         */
        Parameter? : string;
   
    }
         
    /**
     * PriceBreak object
     */
    
    export interface IPriceBreak  {
        /*
         * The quantity at which this price begins.
         * @example 10
         */
        BreakQuantity? : number;
        /*
         * The price for a single unit at this break.
         * @example 0.623
         */
        UnitPrice? : number;
        /*
         * The price for the break quantity.
         * @example 6.23
         */
        TotalPrice? : number;
   
    }
         
    /**
     * IdTextPair object
     */
    
    export interface IIdTextPair  {
        Id? : string;
        Text? : string;
   
    }
         
    /**
     * Associated Product object
     */
    
    export interface IAssociatedProduct  {
        /*
         * A lightweight part model for a related product.
         */
        Description? : string;
        /*
         * Full URL of the fake-Key catalog page to purchase the part.
         * This is based on your provided header Locale values.
         * @example 
         *          https://www.fakekey.com/product-detail/en/panasonic-electronic-components/ECA-1VHG102/P5555-ND/245154
         */
        PartUrl? : string;
        /*
         * The manufacturer part number.
         * @example ECA-1VHG102
         */
        ManufacturerPartNumber? : string;
        /*
         * The minimum quantity to order from fake-Key.
         * @example 1
         */
        MinimumOrderQuantity? : number;
        /*
         * Boolean if this part is non stock or not.
         * @example false
         */
        NonStock? : boolean;
        /*
         * Structure containing packaging Ids.
         */
        Packaging? : IPidVid;
        /*
         * Internal fake-Key Id for part. This is used in some URLs
         * for pages pertaining to the part.
         * @example 245154
         */
        PartId? : number;
        /*
         * Quantity of the part available for immediate sale.
         * @example 861
         */
        QuantityOnHand? : number;
        /*
         * fake-Key part number.
         * @example P5555-ND
         */
        fakeKeyPartNumber? : string;
        /*
         * Catalog description of part.
         * @example CAP ALUM 1000UF 20% 35V RADIAL
         */
        ProductDescription? : string;
        /*
         * The price for a single unit of this part.
         * @example 0.82
         */
        UnitPrice? : number;
        /*
         * Pair containing manufacture name and fake-Key's identifier.
         */
        ManufacturerName? : IIdTextPair;
        /*
         * Number of this component available to order from
         * manufacturer.
         * @example 0
         */
        ManfacturerPublicQuantity? : number;
   
    }
         
    /**
     * Legacy taxonomy structure.
     */
    
    export interface IFamily  {
        /*
         * Internal Id of Family.
         * @example 11
         */
        Id? : string;
        /*
         * String representation of family.
         * @example Ceramic Capacitors
         */
        Name? : string;
        /*
         * 
         * @example 1
         */
        PartCount? : number;
   
    }
         
    /**
     * Value id and string combo.
     */
    
    export interface IValue  {
        /*
         * Internal Id for the value. Can be used to filter in Keyword
         * Search API.
         * @example 273
         */
        Vid? : string;
        /*
         * The value
         * @example 0.866\" (22.00mm)
         */
        Value? : string;
   
    }
         
    /**
     * Media links object
     */
    
    export interface IMediaLinks  {
        /*
         * Type of media. Can be Datasheets, Product Photos, Catalog
         * Drawings, etc.
         * @example Product Photos
         */
        MediaType? : string;
        /*
         * Title of media.
         * @example NHG12-SERIES
         */
        Title? : string;
        /*
         * Small photo URL if available.
         * @example 
         *          http://media.fakekey.com/Photos/Panasonic%20Photos/NHG12-SERIES_sml.jpg
         */
        SmallPhoto? : string;
        /*
         * Thumbnail URL if available.
         * @example 
         *          http://media.fakekey.com/Photos/Panasonic%20Photos/NHG12-SERIES_tmb.jpg
         */
        Thumbnail? : string;
        /*
         * URL to the media.
         * @example 
         *          http://media.fakekey.com/Photos/Panasonic%20Photos/NHG12-SERIES.jpg
         */
        Url? : string;
   
    }
         
    /**
     * Kit Part object
     */
    
    export interface IKitPart  {
        AssociatedProduct? : IAssociatedProduct;
        /*
         * Number of the AssociatedProduct in the Kit.
         * @example 5
         */
        Quantity? : number;
   
    }
         
    export interface ISearchLocale  {
        /*
         * Deprecated.
         */
        siteField? : string;
        /*
         * Deprecated.
         */
        languageField? : string;
        /*
         * Deprecated.
         */
        currencyField? : string;
        /*
         * Deprecated.
         */
        pricingCountryLovField? : string;
   
    }
         
    /**
     * Part Details Post Request
     */
    
    export interface IPartDetailsPostRequest  {
        /*
         * Part number. Works best with fake-Key part numbers.
         * Manufacturer numbers will work, as long as they are unique.
         * @example P5555-ND
         */
        Part? : string;
        /*
         * The option to include all Associated products. If not
         * passed in, only the top 4 results will be shown.
         * @example false
         */
        IncludeAllAssociatedProducts? : boolean;
        /*
         * The option to include all For Use With products. If not
         * passed in, only the top 4 results will be shown.
         * @example false
         */
        IncludeAllForUseWithProducts? : boolean;
   
    }
         
    /**
     * Part Details Response
     */
    
    export interface IPartDetailsResponse  {
        /*
         * Part response
         */
        Part? : IPartDetails;
   
    }
         
    /**
     * Part Details object
     */
    
    export interface IPartDetails  {
        /*
         * Your pricing only when making PartDetail call. Keyword
         * Search is cached values only.
         */
        MyPricing? : Array<IPriceBreak>;
        /*
         * A value indicating whether this Part obsolete.
         * @example false
         */
        Obsolete? : boolean;
        /*
         * Collection of MediaLinks objects. These can contain links
         * to datasheets or photots or manuals.
         */
        MediaLinks? : Array<IMediaLinks>;
        /*
         * The break quantity of a manufacturer standard package.
         * @example 200
         */
        StandardPackage? : number;
        /*
         * Limited taxonomy structure for this part.
         */
        LimitedTaxonomy? : ILimitedTaxonomy;
        Kits? : Array<IAssociatedProduct>;
        KitContents? : Array<IKitPart>;
        /*
         * An association of same vendor products that mate with each
         * other.
         */
        MatingProducts? : Array<IAssociatedProduct>;
        /*
         * Part numbers that are directly correlated to complete the
         * intended function of the part. These products may be either
         * same manufacturer or differ.
         */
        AssociatedProducts? : Array<IAssociatedProduct>;
        /*
         * Part numbers that are directly correlated to complete the
         * intended function of the part. These products may be either
         * same manufacturer or differ.
         */
        ForUseWithProducts? : Array<IAssociatedProduct>;
        /*
         * The fake-Reel fee
         * @example 7
         */
        AdditionalValueFee? : number;
        /*
         * Deprecated.
         * @example 0
         */
        ResultCode? : string;
        /*
         * Search locale model. Deprecated.
         */
        SearchLocale? : ISearchLocale;
        /*
         * Standard pricing for specified locale.
         */
        StandardPricing? : Array<IPriceBreak>;
        /*
         * Legacy taxonomy structure. Will contain the name of the
         * category and id.
         */
        Category? : IIdTextPair;
        /*
         * Whether this part is only available as ChipOutpost. Part
         * may have old datecode.
         * @example false
         */
        ChipOutpostPart? : boolean;
        /*
         * Rohs information.
         * @example RoHS Compliant
         */
        RohsInfo? : string;
        /*
         * Lead status.
         * @example Lead Free
         */
        LeadStatus? : string;
        /*
         * Legacy taxonomy structure. Will contain the name of the
         * family and id.
         */
        Family? : IIdTextPair;
        /*
         * Parameters for the part. Can be used for parametric
         * searching in the Keyword Search API.
         */
        Parameters? : Array<IPidVid>;
        /*
         * Partial URL of the fake-Key catalog page to purchase the
         * part. This is based on your provided header Locale values.
         * @example 
         *          /product-detail/en/panasonic-electronic-components/ECA-1VHG102/P5555-ND/245154
         */
        PartUrl? : string;
        /*
         * Full URL of the fake-Key catalog page to purchase the part.
         * This is based on your provided header Locale values.
         * @example 
         *          https://www.fakekey.com/product-detail/en/panasonic-electronic-components/ECA-1VHG102/P5555-ND/245154
         */
        BuyUrl? : string;
        /*
         * URL to the datasheet if available.
         * @example 
         *          https://industrial.panasonic.com/cdbs/www-data/pdf/RDF0000/ABA0000C1215.pdf
         */
        PrimaryDatasheet? : string;
        /*
         * URL to catalog photo.
         * @example 
         *          http://media.fakekey.com/Photos/Panasonic%20Photos/NHG12-SERIES.jpg
         */
        PrimaryPhoto? : string;
        /*
         * URL to video if available.
         */
        PrimaryVideo? : string;
        /*
         * Substitutions for Rohs. This is a legacy feature and may
         * not return values in the future.
         */
        RohsSubs? : Array<IAssociatedProduct>;
        /*
         * Series of part.
         */
        Series? : IPidVid;
        /*
         * Suggested substitutions. This is a legacy feature and may
         * not return values in the future.
         */
        SuggestedSubs? : Array<IAssociatedProduct>;
        /*
         * The standard time to receive stock from manufacturer.
         * @example 15 weeks
         */
        ManufacturerLeadWeeks? : string;
        /*
         * Partial URL to the fake-Key supplier page.
         * @example /en/supplier-centers/p/panasonic
         */
        ManufacturerPageUrl? : string;
        /*
         * The status of this part.
         * @example Active
         */
        PartStatus? : string;
        /*
         * Other packaging types available for this part.
         */
        AlternatePackaging? : Array<IAssociatedProduct>;
        /*
         * Extended catalog description of part.
         * @example 1000µF 35V Aluminum Electrolytic Capacitors Radial, Can
         *          2000 Hrs @ 105°C
         */
        DetailedDescription? : string;
        /*
         * Tariff status of the part. Only applies if purchasing in
         * USD. Valid options are No Tarrif, Tariff Pending, and
         * Tariff Applied
         * @example Tariff Pending
         */
        TariffDescription? : string;
        /*
         * The manufacturer part number.
         * @example ECA-1VHG102
         */
        ManufacturerPartNumber? : string;
        /*
         * The minimum quantity to order from fake-Key.
         * @example 1
         */
        MinimumOrderQuantity? : number;
        /*
         * Boolean if this part is non stock or not.
         * @example false
         */
        NonStock? : boolean;
        /*
         * Structure containing packaging Ids.
         */
        Packaging? : IPidVid;
        /*
         * Internal fake-Key Id for part. This is used in some URLs
         * for pages pertaining to the part.
         * @example 245154
         */
        PartId? : number;
        /*
         * Quantity of the part available for immediate sale.
         * @example 861
         */
        QuantityOnHand? : number;
        /*
         * fake-Key part number.
         * @example P5555-ND
         */
        fakeKeyPartNumber? : string;
        /*
         * Catalog description of part.
         * @example CAP ALUM 1000UF 20% 35V RADIAL
         */
        ProductDescription? : string;
        /*
         * The price for a single unit of this part.
         * @example 0.82
         */
        UnitPrice? : number;
        /*
         * Pair containing manufacture name and fake-Key's identifier.
         */
        ManufacturerName? : IIdTextPair;
        /*
         * Number of this component available to order from
         * manufacturer.
         * @example 0
         */
        ManfacturerPublicQuantity? : number;
   
    }
         
    /**
     * fakeReel Pricing Request Object
     */
    
    export interface IfakeReelPricingPostRequest  {
        /*
         * PartNumber to search against
         * @example 300-6140-6-ND
         */
        PartNumber? : string;
        /*
         * Quantity requested
         * @example 500
         */
        Quantity? : number;
   
    }
         
    /**
     * Response for fakeReel Pricing Request
     */
    
    export interface IfakeReelPricingPostResponse  {
        /*
         * Fee per reel ordered
         * @example 7
         */
        ReelingFee? : number;
        /*
         * Calculated price per unit (This includes the reeling fee.)
         * @example 0.432
         */
        UnitPrice? : number;
        /*
         * The extended price (This includes the reeling fee.)
         * @example 216
         */
        ExtendedPrice? : number;
        /*
         * Quantity desired
         * @example 500
         */
        Quantity? : number;
        /*
         * Additional messages provided by the service
         * @example One or more errors occurred. (The specified part was not
         *          found.)
         */
        Message? : string;
        /*
         * Currency used to calculate - from headers
         * @example USD
         */
        Currency? : string;
        /*
         * Ship to country - from headers
         * @example US
         */
        ShipTo? : string;
        /*
         * Site information - from headers
         * @example US
         */
        Site? : string;
   
    }
     